### ISSUE TITLE
How to Handle CORS issue?

### ISSUE THREAD

**Issue by beezay** [dahsameer/nepse-api-helper#2] opened 2022-06-30 07:12 UTC
![image](https://user-images.githubusercontent.com/59993093/176615124-725c4d3f-5c7e-433f-a9c3-89192e6f59f6.png)
I find this error while implementing the code.
Snippet of Code Here...
![image](https://user-images.githubusercontent.com/59993093/176615279-d93bb7d7-68c6-46b7-96eb-4121ead9fd4c.png)
 When fetchId is called CORS error is shown.
 
![image](https://user-images.githubusercontent.com/59993093/176615408-c718ae0b-6567-4da9-8170-6ec5e8fbe6e6.png)

**Comment by dahsameer** [comment] 2022-06-30 07:34
CORS is a policy that is implemented by browsers. It can in no way be bypassed by us. The only way would be to create a API server which acts as proxy and forwards all the request from your react app to Nepse API.

Your React App  ->  Web API server  ->  Nepse

**Comment by beezay** [comment] 2022-06-30 09:00
Hello Sammer,

Could you please provide the means to communicate with you.

As we tried implementing the code for NEPSE-API but facing problem.

Hope you might help us.

Regards

**Comment by dahsameer** [comment] 2022-06-30 11:39
email visible on my profile now

**Comment by dahsameer** [comment] 2022-07-13 12:44
closing the issue as the issue is not with library. this library is not meant to be used in a browser,

**Closed as not planned by dahsameer** 2022-07-13 12:44 UTC
